services:
  web:
    build: ../apps/web
    ports:
      - "3000:80"
    depends_on:
      - keycloak
    env_file:
      - ../apps/web/.env.development

  api:
    build: ../apps/api
    ports:
      - "5001:8080"
    depends_on:
      - postgress
      - keycloak
    env_file:
      - ../apps/api/WebGen.Api/.env.development

  postgress:
    image: pgvector/pgvector:pg18-trixie
    container_name: postgress_vector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webgen
    ports:
      - "5432:5432"
    volumes:
      - ./postgress:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
      - ./keycloak/themes:/opt/keycloak/themes